# Server settings
server.address=0.0.0.0
server.port=8083
server.servlet.context-path=/api

# Application name
spring.application.name=dis-news-service

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3306/dis_news?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ulaanbaatar}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Static resources & encoding
spring.web.resources.static-locations=classpath:/static/
spring.web.encoding.charset=UTF-8
spring.web.encoding.enabled=true
spring.web.encoding.force=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
